apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: demo-pool
  namespace: metallb-system
spec:
  addresses:
    # replace the following with your IP address range
    - <194.1.2.100-194.1.2.110>
